version: "2"
services:

  redis: # ok
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    restart: always

#  mailhog: # ok
#    image: mailhog/mailhog:latest
#    container_name: mailhog
#    ports:
#      - "8025:8025"
#    restart: always

  mysql: # ok
    image: wodby/mariadb
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - "./data/db:/var/lib/mysql"
#      - ./mariadb-init:/docker-entrypoint-initdb.d # Place init .sql file(s) here.
#      - /path/to/mariadb/data/on/host:/var/lib/mysql # I want to manage volumes manually.
    ports:
      - "3306:3306"

  phpmyadmin: # ok
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin
      depends_on:
        - mysql
      environment:
        PMA_USER: root
        PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        PMA_ARBITRARY: 1
        PMA_HOST: mysql
      ports:
        - "8080:80"
      restart: always

  nginx:
    image: nginx:alpine # ok
    container_name: nginx
    depends_on:
      - phpfpm
      - mysql
    environment:
      NGINX_STATIC_CONTENT_OPEN_FILE_CACHE: "off"
      NGINX_ERROR_LOG_LEVEL: debug
      NGINX_BACKEND_HOST: phpfpm
      NGINX_SERVER_ROOT: /var/www/html
    volumes:
#   WP
      - "./wordpress:/var/www/html"
#   OC
#     - "./opencart/upload:/var/www/html"
      - "./config/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "./config/nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./config/certs:/etc/nginx/certs"
      - "./logs/nginx:/var/log/nginx"
    ports:
      - "80:80"
      - "443:443"
    restart: always

  phpfpm: # to build !!!
    image: wodby/php:7.4 # works
    container_name: phpfpm
    environment:
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025 # works on wodby
    volumes:
      - "./wordpress:/var/www/html"
    restart: always